/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Adapter Address": {                             "en": "Adapter Address",                                 "de": "Adapter Adresse",                                 "ru": "Собственный адрес",                               "pt": "Endereço do adaptador",                           "nl": "Adapter adres",                                   "fr": "Adresse de l'adaptateur",                         "it": "Indirizzo dell'adattatore",                       "es": "Dirección del adaptador",                         "pl": "Adres adaptera",                                  "zh-cn": "适配器地址"},
    "Adapter Callback Address": {                    "en": "Adapter Callback Address",                        "de": "Adapter Callback Adresse",                        "ru": "Собственный Callback адрес",                      "pt": "Endereço de retorno de chamada do adaptador",     "nl": "Adapter-callback-adres",                          "fr": "Adresse de rappel de l'adaptateur",               "it": "Indirizzo di richiamata dell'adattatore",         "es": "Dirección de devolución de llamada del adaptador", "pl": "Adres zwrotny adaptera",                          "zh-cn": "适配器回调地址"},
    "Adapter Port": {                                "en": "Adapter Port",                                    "de": "Adapter Port",                                    "ru": "Порт драйвера ioBroker",                          "pt": "Porta adaptadora",                                "nl": "Adapterpoort",                                    "fr": "Port de l'adaptateur",                            "it": "Porta dell'adattatore",                           "es": "Puerto adaptador",                                "pl": "Port adaptera",                                   "zh-cn": "适配器端口"},
    "Additional settings": {                         "en": "Additional settings",                             "de": "Zusätzliche Einstellungen",                       "ru": "Дополнительные настройки",                        "pt": "Configurações adicionais",                        "nl": "Aanvullende instellingen",                        "fr": "Paramètres additionnels",                         "it": "Altre impostazioni",                              "es": "Ajustes adicionales",                             "pl": "Dodatkowe ustawienia",                            "zh-cn": "其他设置"},
    "BIN-RPC does not work with HTTPS. HTTPS has been disabled.": {"en": "BIN-RPC does not work with HTTPS. HTTPS has been disabled.", "de": "BIN-RPC ist nicht HTTPS kompatibel. HTTPS wurde deaktiviert.", "ru": "BIN-RPC не работает с HTTPS. HTTPS отключен.",    "pt": "O BIN-RPC não funciona com HTTPS. HTTPS foi desativado.", "nl": "BIN-RPC werkt niet met HTTPS. HTTPS is uitgeschakeld.", "fr": "BIN-RPC ne fonctionne pas avec HTTPS. HTTPS a été désactivé.", "it": "BIN-RPC non funziona con HTTPS. HTTPS è stato disabilitato.", "es": "BIN-RPC no funciona con HTTPS. HTTPS ha sido desactivado.", "pl": "BIN-RPC nie działa z HTTPS. HTTPS został wyłączony.", "zh-cn": "BIN-RPC不适用于HTTPS。 HTTPS已被禁用。"},
    "Check communication interval (sec)": {          "en": "Check communication interval(sec)",               "de": "Verbindungs-Test Intervall(s)",                   "ru": "Интервал проверки соединения(сек)",               "pt": "Verifique o intervalo de comunicação (seg)",      "nl": "Controleer communicatie-interval (sec)",          "fr": "Vérifier l'intervalle de communication (sec)",    "it": "Controllare l'intervallo di comunicazione (sec)", "es": "Verificar el intervalo de comunicación (sec)",    "pl": "Sprawdź interwał komunikacji (s)",                "zh-cn": "检查通信间隔（秒）"},
    "Daemon": {                                      "en": "Daemon",                                          "de": "Daemon",                                          "ru": "Служба",                                          "pt": "Daemon",                                          "nl": "Demon",                                           "fr": "Démon",                                           "it": "Demone",                                          "es": "Demonio",                                         "pl": "Daemon",                                          "zh-cn": "守护进程"},
    "Don't delete devices": {                        "en": "Don't delete devices on adapter start",           "de": "Geräte nicht löschen bei Adapterstart",           "ru": "Не удаляйте устройства при старте адаптера",      "pt": "Não exclua dispositivos na inicialização do adaptador", "nl": "Verwijder geen apparaten bij het starten van de adapter", "fr": "Ne supprimez pas les périphériques au démarrage de l'adaptateur", "it": "Non eliminare i dispositivi all'avvio dell'adattatore", "es": "No elimine dispositivos al iniciar el adaptador", "pl": "Nie usuwaj urządzeń przy uruchamianiu adaptera",  "zh-cn": "不要在适配器启动时删除设备"},
    "Force objects re-init": {                       "en": "Synchronize objects (once)",                      "de": "Geräte neu einlesen (einmalig)",                  "ru": "Синхронизировать объекты (один раз)",             "pt": "Sincronizar objetos (uma vez)",                   "nl": "Synchroniseer objecten (één keer)",               "fr": "Synchroniser des objets (une fois)",              "it": "Sincronizza oggetti (una volta)",                 "es": "Sincronizar objetos (una vez)",                   "pl": "Synchronizuj obiekty (raz)",                      "zh-cn": "同步对象（一次）"},
    "HomeMatic Address": {                           "en": "HomeMatic Address",                               "de": "HomeMatic Adresse",                               "ru": "Адрес HomeMatic",                                 "pt": "Endereço HomeMatic",                              "nl": "HomeMatic-adres",                                 "fr": "Adresse de HomeMatic",                            "it": "Indirizzo HomeMatic",                             "es": "Dirección HomeMatic",                             "pl": "Adres HomeMatic",                                 "zh-cn": "HomeMatic地址"},
    "HomeMatic Port": {                              "en": "HomeMatic Port",                                  "de": "HomeMatic Port",                                  "ru": "Порт HomeMatic",                                  "pt": "HomeMatic Port",                                  "nl": "HomeMatic-poort",                                 "fr": "AccueilMatic Port",                               "it": "HomeMatic Port",                                  "es": "Puerto HomeMatic",                                "pl": "Port HomeMatic",                                  "zh-cn": "HomeMatic港口"},
    "Homematic RPC adapter settings": {              "en": "Homematic RPC adapter settings",                  "de": "Homematic RPC Adapter Einstellungen",             "ru": "Настройки Homematic RPC драйвера",                "pt": "Configurações do adaptador Homematic RPC",        "nl": "Homematische RPC-adapterinstellingen",            "fr": "Paramètres de l'adaptateur RPC homématique",      "it": "Impostazioni dell'adattatore RPC Homematic",      "es": "Configuración del adaptador Homematic RPC",       "pl": "Homematyczne ustawienia adaptera RPC",            "zh-cn": "Homematic RPC适配器设置"},
    "Listen on all IPs": {                           "en": "Listen on all IPs",                               "de": "Anfragen für alle IPs beantworten",               "ru": "Слушать на всех IP адресах",                      "pt": "Ouça todos os IPs",                               "nl": "Luister op alle IP's",                            "fr": "Écoutez sur toutes les adresses IP",              "it": "Ascolta su tutti gli IP",                         "es": "Escuchar en todas las direcciones IP",            "pl": "Posłuchaj na wszystkich IP",                      "zh-cn": "收听所有IP"},
    "Ok": {                                          "en": "Ok",                                              "de": "Ok",                                              "ru": "Ok",                                              "pt": "Está bem",                                        "nl": "OK",                                              "fr": "D'accord",                                        "it": "Ok",                                              "es": "De acuerdo",                                      "pl": "Ok",                                              "zh-cn": "好"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Please specify callback address": {             "en": "Please specify callback address.",                "de": "Bitte Callback IP-Adresse eingeben.",             "ru": "Введите IP адрес для callback.",                  "pt": "Por favor, especifique o endereço de retorno de chamada.", "nl": "Geef het callback-adres op.",                     "fr": "Veuillez spécifier l'adresse de rappel.",         "it": "Si prega di specificare l'indirizzo di richiamata.", "es": "Por favor, especifique la dirección de devolución de llamada.", "pl": "Proszę podać adres zwrotny.",                     "zh-cn": "请指定回拨地址。"},
    "Protocol": {                                    "en": "Protocol",                                        "de": "Protokoll",                                       "ru": "Протокол",                                        "pt": "Protocolo",                                       "nl": "Protocol",                                        "fr": "Protocole",                                       "it": "Protocollo",                                      "es": "Protocolo",                                       "pl": "Protokół",                                        "zh-cn": "协议"},
    "Reconnect interval (sec)": {                    "en": "Reconnect interval (sec)",                        "de": "Wiederverbindungs-Intervall(sek)",                "ru": "Интервал повтора соединения(сек)",                "pt": "Intervalo de Reconexão (segundo)",                "nl": "Verbindingsinterval opnieuw verbinden (sec)",     "fr": "Intervalle de reconnexion (sec)",                 "it": "Intervallo di riconnessione (sec)",               "es": "Intervalo de reconexión (sec)",                   "pl": "Interwał ponownego połączenia (s)",               "zh-cn": "重新连接间隔（秒）"},
    "This IP is unreachable from %s": {              "en": "This IP is unreachable from %s",                  "de": "Diese IP ist nicht erreichbar von %s",            "ru": "Этот IP не доступен для %s",                      "pt": "Este IP é inacessível de %s",                     "nl": "Deze IP is onbereikbaar van %s",                  "fr": "Cette adresse IP est inaccessible depuis %s",     "it": "Questo IP non è raggiungibile da %s",             "es": "Este IP es inalcanzable desde %s",                "pl": "To IP jest nieosiągalne z %s",                    "zh-cn": "此IP无法从％s访问 %s"},
    "Use https": {                                   "en": "Use https",                                       "de": "HTTPS benutzen",                                  "ru": "использовать https",                              "pt": "use https",                                       "nl": "gebruik https",                                   "fr": "utiliser https",                                  "it": "usa https",                                       "es": "usar https",                                      "pl": "użyj https",                                      "zh-cn": "使用https"},
    "Username": {                                    "en": "Username",                                        "de": "Benutzername",                                    "ru": "имя пользователя",                                "pt": "Username",                                        "nl": "Gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "Nome utente",                                     "es": "Nombre de usuario",                               "pl": "Nazwa Użytkownika",                               "zh-cn": "用户名"},
};